// Normal play and isolated before/after fixtures use different origins to protect player saves.
const http=require('http'),fs=require('fs'),path=require('path');
const BASE=path.resolve(__dirname,'../..'),OUT=path.join(BASE,'outputs/bottle-quality');
const comparison=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>보트리스 병·물 연출 비교</title>
<style>body{margin:24px;background:#0f171c;color:#e7f3f5;font:15px system-ui}h1{font-size:22px}p{color:#afc7cf}button,select{padding:10px 16px;margin:3px;border:1px solid #557080;border-radius:8px;background:#1b2830;color:inherit;font:inherit}main{display:flex;gap:20px;flex-wrap:wrap}iframe{width:390px;height:844px;border:1px solid #557080;border-radius:16px}h2{font-size:16px}</style>
<h1>병과 물 연출 — 전후 비교</h1><p>같은 8병 상태의 검증용 화면입니다. 게임 기록은 저장하지 않습니다. 효과 재생은 이 브라우저의 동작 줄이기 설정을 따릅니다.</p>
<select id="skin"><option value="lab">기본 유리</option><option value="cafe">카페</option><option value="gem">보석</option><option value="deep">심해</option></select><button onclick="reload()">초기화</button><button onclick="play('pour')">붓기</button><button onclick="play('place')">조각 착지</button><button onclick="play('clear')">물병 정리</button><button onclick="play('high')">높은 콤보</button>
<main><section><h2>수정 전</h2><iframe id="before" title="수정 전 검증 화면" src="/before"></iframe></section><section><h2>수정 후</h2><iframe id="after" title="수정 후 검증 화면" src="/after"></iframe></section></main>
<script>const frames=()=>['before','after'].map(id=>document.getElementById(id));function reload(){for(const f of frames())f.src='/'+f.id+'?skin='+document.getElementById('skin').value;}document.getElementById('skin').onchange=reload;
function play(kind){for(const f of frames()){const w=f.contentWindow;w.__fixture({streak:kind==='high'?6:3});}setTimeout(()=>{for(const f of frames()){const d=f.contentDocument;const click=s=>d.querySelector(s).click();if(kind==='place'){click('#cup');click('#rack [data-i="6"]');}else{click('#rack [data-i="'+(kind==='pour'?0:3)+'"]');click('#rack [data-i="'+(kind==='pour'?5:2)+'"]');}}},220);}</script></html>`;
http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(fs.readFileSync(path.join(BASE,'dist/index.html')));}).listen(8154,'127.0.0.1',()=>console.log('Play: http://127.0.0.1:8154/'));
http.createServer((req,res)=>{const p=new URL(req.url,'http://localhost').pathname;const file=p==='/before'?'before-test.html':p==='/after'?'after-test.html':null;res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(file?fs.readFileSync(path.join(OUT,file)):comparison);}).listen(8155,'127.0.0.1',()=>console.log('Comparison: http://127.0.0.1:8155/'));
