// Isolated review fixture generated by node uitest/i18n.js.
const http = require('http'), fs = require('fs'), path = require('path');
const file = path.resolve(__dirname, '../../outputs/i18n/test.html');
http.createServer((req,res) => {
  res.writeHead(200, {'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});
  res.end(fs.readFileSync(file));
}).listen(8139,'127.0.0.1',()=>console.log('I18N review http://127.0.0.1:8139/'));
